// kotlinx-io reads `import.meta`, which is a syntax error inside the eval() wrappers generated by
// Kotlin's default EvalSourceMapDevToolPlugin, even when the bundle is loaded as an ES module
config.plugins = config.plugins.filter(plugin => plugin.constructor.name !== 'EvalSourceMapDevToolPlugin');
if (config.mode === 'development') {
    config.devtool = 'source-map';
}
